var mongoose = require("mongoose");

var teamSchema = new mongoose.Schema({
    name: String,
    mainImage: String,
    email: String,
    type: String,
    description: String,
    carouselImages: [String],
    flavourText: String,
    socialMedia: [[String, String]],
    quotes: [[String, String]],
    tags: String
});

var team = mongoose.model("Team", teamSchema);
teams[0] = new team({name:"Software Engineering Society", mainImage: "software-eng-pic.png", email: "ses@mcmaster.ca", type: "Academic", description: "Software is making a huge impact on society and is more accessible than ever to society <br/>Our mission is to encourage a student initiative in software-related projects and to promote events that integrate the students and the faculty. It is an opportunity to gain experience and network with those in the field of Software Engineering and its related disciplines. ", carouselImages: ["software-1.jpg","software-2.jpg","software-3.png"], flavourText: "Software is a great combination between artistry and engineering", socialMedia: ["a","b"], quotes: [["Software design is for everyone, young and old, male and female","- Jayanthi Uthayakumar, Club President"],["Software design is for everyone, young and old, male and female","- Jayanthi Uthayakumar, Club President"]], tags: "software, coding, design, technology, web"});
teams[1] = new team({name:"Engineers without Borders McMaster Chapter", mainImage: "mac-ewb.jpg", email: "ewb@mcmaster.ca", type: "Volunteer", description: "We create a community of emerging leaders, creative thinkers and innovators, and together we work across borders, without boundaries, to build upon our similarities and learn from our differences. We develop leaders and we invest in one another to create change at every level. Our vision is a world where everyone’s basic needs are met and where everyone can live to their full potential. Our mission is to catalyze changes that address the root causes of poverty and inequity by investing in people and ideas that will contribute to building an equitable and sustainable world.", carouselImages: ["ewb-1.png","ewb-2.png"], flavourText: "We develop leaders and use engineering to create a sustainable future", socialMedia: ["c","d"], quotes: [["At Engineers Without Borders Canada, we strive to unlock human potential","Engineers without Borders Canada"],["At Engineers Without Borders Canada, we strive to unlock human potential","Engineers without Borders Canada"]], tags: "volunteer, global, engineering, community, outreach, leadership development, advocacy"});
teams[2] = new team({name:"Chess Club", mainImage: "chess-club.png", email: "chess@mcmaster.ca", type: "Games", description: "McMaster's Chess Club provides a friendly community of chess-playing students of all skill levels. With regular weekly meetings in the Student Centre students can come out and play casual or serious chess matches each other.", carouselImages: ["chess-1.png","chess-2.jpg","chess-3.jpg"], flavourText: "The beauty of chess is it can be whatever you want it to be. Whatever your circumstances, anyone can enjoy a good fight to the death over the chess board", socialMedia: ["e","f"], quotes: [["We work to create a sustainable world for the benefit of people and the environment everywhere.","- Jane, McMaster Chapter President"],["We work to create a sustainable world for the benefit of people and the environment everywhere.","- Jane, McMaster Chapter President"]], tags: "chess, strategy, logic, puzzle"});
teams[3] = new team({name:"Board Game Society", mainImage: "board-games.jpg", email: "games@mcmaster.ca", type: "Games", description: "The McMaster Board Game Society is home to a smorgasbord of board and card games. You name the genre, and we've got a game for you! Cooperative, Euro games, Secret Identity, Deck builders - these are just some of the different types of games we have for you to play.Not an expert? Don't worry, our club execs have been playing board games for years and can get you started and having fun in no time!", carouselImages: ["games-1.jpg","games-2.jpg, games-3.jpg"], flavourText: "If you're not prepared to lose every friend you have over a board game, you're not playing hard enough", socialMedia: ["g","h"], quotes: [["Avoid the crowd. Do your own thinking independently. Be the chess player, not the chess piece.","- Ralph Charell"],["Avoid the crowd. Do your own thinking independently. Be the chess player, not the chess piece.","- Ralph Charell"]], tags: "gaming, board games, strategy, leisure"});
teams[4] = new team({name:"McMaster Improv Team", mainImage: "improv.png", email: "improv@mcmaster.ca", type: "Theatre", description: "The McMaster Improv Team provides a safe and friendly environment for everyone who wishes to develop their skills or perform. With regular mettings and usually at least one show a month, it's a great way to express your talent and inner creativity!", carouselImages: ["improv-1.png","improv-2.png"], flavourText: "The McMaster Improv Team is full of excitement and fun at every turn", socialMedia: ["i","j"], quotes: [["Our goal is to unite the McMaster community, providing our large and growing library of games to any clubs or individuals who need it.","- John, Club Admin"],["Our goal is to unite the McMaster community, providing our large and growing library of games to any clubs or individuals who need it.","- John, Club Admin"]], tags: "improv, theatre, acting, drama, performance, stage, comedy"});
teams[5] = new team({name:"Geocaching Group", mainImage: "geocache-logo.png", email: "geo@mcmaster.ca", type: "Outdoor", description: "Geocaching is an amazing way to discover new places and explore familiar places. It brings adventure and challenge, and it a great way to get outside and have fun. It lets you experience new places like a local, and discover places you never knew existed despite being there a million times. It's a great experience.", carouselImages: ["geo-1.png","geo-2.png"], flavourText: "Geocaching brings exploration of the finer points of nature to the digital age", socialMedia: ["k","l"], quotes: [["To perform or not to perform - there is no question","- Bob, Coordinator"],["To perform or not to perform - there is no question","- Bob, Coordinator"]], tags: "geocaching, outdoor, adventure, GPS, explore"});
teams[6] = new team({name:"Toastmasters", mainImage: "toastmasters.png", email: "speak@mcmaster.ca", type: "Public Speaking", description: "Do you want to become a confident public speaker and strong leader? If so, Toastmasters is the place for you. You’ll find a supportive learn-by-doing environment that allows you to achieve your goals at your own pace. Toastmasters International is a world leader in communication and leadership developmentLearn how Toastmasters has changed the lives of members.", carouselImages: ["speak-1.png","speak-2.png"], flavourText: "Every Toastmaster's journey starts with a single speech", socialMedia: ["m","n"], quotes: [["Geocaching is an amazing way to explore new places!","- Adam, Geocacher"],["Geocaching is an amazing way to explore new places!","- Adam, Geocacher"]], tags: "public speaking, leadership, speech, communication, development"});

module.exports = team;